a=int(input("enter a number: "))
b=int(input("enter b number: "))
print("sum :", a+b)
print("difference :",a-b)
print("multiplcation :",a*b)
print("division :",a/b)
print("modulus :",a%b)
print("power :",a**b)
print("floor division :",a//b)